version: '3'

services:
  web:
    image: django_menu:1
    container_name: 'tree'
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/django_test
    ports:
      - 8000:8000

