# Generated by Django 4.1.7 on 2023-03-06 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangotest', '0002_remove_itemstree_parent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemstree',
            name='child_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='itemstree_child', to='djangotest.item'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemstree',
            name='parent_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='itemstree_parent', to='djangotest.item'),
            preserve_default=False,
        ),
    ]
