# Generated by Django 4.1.7 on 2023-03-06 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangotest', '0003_itemstree_child_id_itemstree_parent_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='item',
            name='parent_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='djangotest.item'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemstree',
            name='nearest_parent_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='itemstree_nearest_parent', to='djangotest.item'),
            preserve_default=False,
        ),
    ]
