# Generated by Django 4.1.7 on 2023-03-06 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangotest', '0004_alter_item_options_item_parent_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemstree',
            name='nearest_parent_id',
        ),
        migrations.AlterField(
            model_name='item',
            name='parent_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='djangotest.item'),
        ),
    ]
