# Generated by Django 4.1.7 on 2023-03-06 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangotest', '0005_remove_itemstree_nearest_parent_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangotest.item'),
        ),
    ]
