# Generated by Django 4.1.7 on 2023-03-10 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangotest', '0007_alter_itemstree_parent_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['name'], 'verbose_name': 'Пункты меню', 'verbose_name_plural': 'Пункты меню'},
        ),
        migrations.RenameField(
            model_name='item',
            old_name='parent_id',
            new_name='parent',
        ),
        migrations.RenameField(
            model_name='itemstree',
            old_name='child_id',
            new_name='child',
        ),
        migrations.RenameField(
            model_name='itemstree',
            old_name='parent_id',
            new_name='parent',
        ),
    ]
